<a href="https://colab.research.google.com/github/Nassemm/NASSEM-MAHARMEH-PORTFOLLIO/blob/main/replication_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!/usr/bin/env python3


import numpy as np
import pandas as pd
import statsmodels.api as sm


def ols(y, X):
    Xc = sm.add_constant(X, has_constant="add")
    return sm.OLS(y, Xc, missing="drop").fit()


def main(xlsx_path: str):
    df = pd.read_excel(xlsx_path, sheet_name="MRW1992data").copy()

    # Core variables
    df["ln_y85"] = np.log(df["rgdpw85"])
    df["ln_s"] = np.log(df["i_y"] / 100.0)

    g_plus_delta = 0.05  # MRW g + δ = 0.05
    df["ln_ngd"] = np.log(df["popgrowth"] / 100.0 + g_plus_delta)

    # Human capital
    # Replace 0 with nan for log transformation
    df["ln_school_frac"] = np.log((df["school"] / 100.0).replace(0, np.nan))
    df["ln_school_pct"] = np.log(df["school"].replace(0, np.nan))

    # Samples
    samples = {
        "Non-oil": df.query("n == 1").copy(),
        "Intermediate": df.query("i == 1").copy(),
        "OECD": df.query("o == 1").copy(),
    }

    # Function to generate table rows and display summaries
    def generate_table_rows_and_summaries(samples_dict, table_num):
        rows = []
        for name, d in samples_dict.items():
            print(f"\n--- {name} Sample - Table {table_num} ---")

            if table_num == "I":
                m_unres = ols(d["ln_y85"], d[["ln_s", "ln_ngd"]])
                print(f"\nUnrestricted OLS Summary for {name} (Table I):")
                display(m_unres.summary())

                d["diff"] = d["ln_s"] - d["ln_ngd"]
                m_res = ols(d["ln_y85"], d[["diff"]])
                print(f"\nRestricted OLS Summary for {name} (Table I):")
                display(m_res.summary())


                rows.append(
                    {
                        "Table": table_num,
                        "Sample": name,
                        "Obs": int(m_unres.nobs),
                        "CONSTANT (unres)": m_unres.params.get("const", np.nan),
                        "ln(I/GDP)": m_unres.params.get("ln_s", np.nan),
                        "ln(n+g+δ)": m_unres.params.get("ln_ngd", np.nan),
                        "P-value (ln(I/GDP)) (unres)": m_unres.pvalues.get("ln_s", np.nan),
                        "P-value (ln(n+g+δ)) (unres)": m_unres.pvalues.get("ln_ngd", np.nan),
                        "R2 (unres)": m_unres.rsquared_adj,
                        "SEE (unres)": np.sqrt(m_unres.mse_resid),
                        "CONSTANT (res)": m_res.params.get("const", np.nan),
                        "[ln(I/GDP) - ln(n+g+δ)]": m_res.params.get("diff", np.nan),
                        "P-value ([ln(I/GDP) - ln(n+g+δ)]) (res)": m_res.pvalues.get("diff", np.nan),
                        "R2 (res)": m_res.rsquared_adj,
                        "SEE (res)": np.sqrt(m_res.mse_resid),
                    }
                )
            elif table_num == "II":
                # Use fraction scaling consistently for Table II
                choice_col = "ln_school_frac"

                m_unres = ols(d["ln_y85"], d[["ln_s", "ln_ngd", choice_col]])
                print(f"\nUnrestricted OLS Summary for {name} (Table II, {choice_col}):")
                display(m_unres.summary())

                d["diff1"] = d["ln_s"] - d["ln_ngd"]
                d["diff2"] = d[choice_col] - d["ln_ngd"]
                m_res = ols(d["ln_y85"], d[["diff1", "diff2"]])
                print(f"\nRestricted OLS Summary for {name} (Table II, {choice_col}):")
                display(m_res.summary())

                rows.append(
                    {
                        "Table": table_num,
                        "Sample": name,
                        "Obs": int(m_unres.nobs),
                        "CONSTANT (unres)": m_unres.params.get("const", np.nan),
                        "ln(I/GDP)": m_unres.params.get("ln_s", np.nan),
                        "ln(n+g+δ)": m_unres.params.get("ln_ngd", np.nan),
                        f"ln(SCHOOL) ({'pct' if choice_col.endswith('pct') else 'frac'})": m_unres.params.get(
                            choice_col, np.nan
                        ),
                        "P-value (ln(I/GDP)) (unres)": m_unres.pvalues.get("ln_s", np.nan),
                        "P-value (ln(n+g+δ)) (unres)": m_unres.pvalues.get("ln_ngd", np.nan),
                        f"P-value (ln(SCHOOL) ({'pct' if choice_col.endswith('pct') else 'frac'})) (unres)": m_unres.pvalues.get(choice_col, np.nan),
                        "R2 (unres)": m_unres.rsquared_adj,
                        "SEE (unres)": np.sqrt(m_unres.mse_resid),
                        "CONSTANT (res)": m_res.params.get("const", np.nan),
                        "[ln(I/GDP) - ln(n+g+δ)]": m_res.params.get("diff1", np.nan),
                        "[ln(SCHOOL) - ln(n+g+δ)]": m_res.params.get("diff2", np.nan),
                        "P-value ([ln(I/GDP) - ln(n+g+δ)]) (res)": m_res.pvalues.get("diff1", np.nan),
                        "P-value ([ln(SCHOOL) - ln(n+g+δ)]) (res)": m_res.pvalues.get("diff2", np.nan),
                        "R2 (res)": m_res.rsquared_adj,
                        "SEE (res)": np.sqrt(m_res.mse_resid),
                    }
                )
        return pd.DataFrame(rows)

    # Table I: Textbook Solow
    table_I = generate_table_rows_and_summaries(samples, "I")

    # Table II: Augmented Solow
    table_II = generate_table_rows_and_summaries(samples, "II")

    #SCHOOL scaling (fraction)
    choice_col = "ln_school_frac"


    # Display Lines
    print("\n MRW Table I Replication:")
    display(table_I.T)
    print("\n MRW Table II Replication:")
    display(table_II.T)
    print(f"\nChosen SCHOOL scaling for Table II: {'percent (0–100)' if choice_col.endswith('pct') else 'fraction (0–1)'}")

    return table_I, table_II
main("MRW1992data.xlsx")

--- Non-oil Sample - Table I ---

Unrestricted OLS Summary for Non-oil (Table I):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.601
Model:                            OLS   Adj. R-squared:                  0.592
Method:                 Least Squares   F-statistic:                     71.51
Date:                Tue, 23 Sep 2025   Prob (F-statistic):           1.13e-19
Time:                        18:52:48   Log-Likelihood:                -101.04
No. Observations:                  98   AIC:                             208.1
Df Residuals:                      95   BIC:                             215.8
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.4299      1.584      3.428      0.001       2.285       8.574
ln_s           1.4240      0.143      9.951      0.000       1.140       1.708
ln_ngd        -1.9898      0.563     -3.532      0.001      -3.108      -0.871
==============================================================================
Omnibus:                        2.881   Durbin-Watson:                   1.453
Prob(Omnibus):                  0.237   Jarque-Bera (JB):                2.631
Skew:                          -0.401   Prob(JB):                        0.268
Kurtosis:                       2.976   Cond. No.                         81.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Restricted OLS Summary for Non-oil (Table I):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.597
Model:                            OLS   Adj. R-squared:                  0.593
Method:                 Least Squares   F-statistic:                     142.4
Date:                Tue, 23 Sep 2025   Prob (F-statistic):           1.13e-20
Time:                        18:52:48   Log-Likelihood:                -101.46
No. Observations:                  98   AIC:                             206.9
Df Residuals:                      96   BIC:                             212.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.8724      0.121     56.995      0.000       6.633       7.112
diff           1.4880      0.125     11.934      0.000       1.241       1.735
==============================================================================
Omnibus:                        4.010   Durbin-Watson:                   1.421
Prob(Omnibus):                  0.135   Jarque-Bera (JB):                3.720
Skew:                          -0.477   Prob(JB):                        0.156
Kurtosis:                       3.015   Cond. No.                         3.15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

--- Intermediate Sample - Table I ---

Unrestricted OLS Summary for Intermediate (Table I):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.599
Model:                            OLS   Adj. R-squared:                  0.588
Method:                 Least Squares   F-statistic:                     53.76
Date:                Tue, 23 Sep 2025   Prob (F-statistic):           5.21e-15
Time:                        18:52:48   Log-Likelihood:                -67.896
No. Observations:                  75   AIC:                             141.8
Df Residuals:                      72   BIC:                             148.7
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.3459      1.543      3.464      0.001       2.270       8.422
ln_s           1.3176      0.171      7.708      0.000       0.977       1.658
ln_ngd        -2.0172      0.534     -3.778      0.000      -3.081      -0.953
==============================================================================
Omnibus:                        6.292   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.043   Jarque-Bera (JB):                5.650
Skew:                          -0.537   Prob(JB):                       0.0593
Kurtosis:                       3.808   Cond. No.                         76.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Restricted OLS Summary for Intermediate (Table I):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.592
Model:                            OLS   Adj. R-squared:                  0.586
Method:                 Least Squares   F-statistic:                     105.8
Date:                Tue, 23 Sep 2025   Prob (F-statistic):           7.58e-16
Time:                        18:52:48   Log-Likelihood:                -68.564
No. Observations:                  75   AIC:                             141.1
Df Residuals:                      73   BIC:                             145.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.0929      0.146     48.711      0.000       6.803       7.383
diff           1.4310      0.139     10.286      0.000       1.154       1.708
==============================================================================
Omnibus:                        8.966   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.011   Jarque-Bera (JB):                8.912
Skew:                          -0.672   Prob(JB):                       0.0116
Kurtosis:                       4.023   Cond. No.                         3.87
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

--- OECD Sample - Table I ---

Unrestricted OLS Summary for OECD (Table I):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.106
Model:                            OLS   Adj. R-squared:                  0.012
Method:                 Least Squares   F-statistic:                     1.126
Date:                Tue, 23 Sep 2025   Prob (F-statistic):              0.345
Time:                        18:52:48   Log-Likelihood:                -8.1659
No. Observations:                  22   AIC:                             22.33
Df Residuals:                      19   BIC:                             25.60
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          8.0206      2.518      3.185      0.005       2.751      13.291
ln_s           0.4999      0.434      1.152      0.264      -0.408       1.408
ln_ngd        -0.7419      0.852     -0.871      0.395      -2.526       1.042
==============================================================================
Omnibus:                        4.010   Durbin-Watson:                   1.796
Prob(Omnibus):                  0.135   Jarque-Bera (JB):                2.575
Skew:                          -0.829   Prob(JB):                        0.276
Kurtosis:                       3.239   Cond. No.                         109.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Restricted OLS Summary for OECD (Table I):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.103
Model:                            OLS   Adj. R-squared:                  0.058
Method:                 Least Squares   F-statistic:                     2.299
Date:                Tue, 23 Sep 2025   Prob (F-statistic):              0.145
Time:                        18:52:48   Log-Likelihood:                -8.2007
No. Observations:                  22   AIC:                             20.40
Df Residuals:                      20   BIC:                             22.58
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          8.6244      0.533     16.172      0.000       7.512       9.737
diff           0.5538      0.365      1.516      0.145      -0.208       1.316
==============================================================================
Omnibus:                        4.283   Durbin-Watson:                   1.855
Prob(Omnibus):                  0.117   Jarque-Bera (JB):                2.818
Skew:                          -0.869   Prob(JB):                        0.244
Kurtosis:                       3.236   Cond. No.                         14.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

--- Non-oil Sample - Table II ---

Unrestricted OLS Summary for Non-oil (Table II, ln_school_frac):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.786
Model:                            OLS   Adj. R-squared:                  0.779
Method:                 Least Squares   F-statistic:                     114.8
Date:                Tue, 23 Sep 2025   Prob (F-statistic):           2.54e-31
Time:                        18:52:48   Log-Likelihood:                -70.576
No. Observations:                  98   AIC:                             149.2
Df Residuals:                      94   BIC:                             159.5
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              6.8444      1.177      5.813      0.000       4.507       9.182
ln_s               0.6967      0.133      5.245      0.000       0.433       0.960
ln_ngd            -1.7452      0.416     -4.196      0.000      -2.571      -0.919
ln_school_frac     0.6545      0.073      9.001      0.000       0.510       0.799
==============================================================================
Omnibus:                        2.001   Durbin-Watson:                   2.124
Prob(Omnibus):                  0.368   Jarque-Bera (JB):                2.008
Skew:                          -0.330   Prob(JB):                        0.366
Kurtosis:                       2.764   Cond. No.                         115.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Restricted OLS Summary for Non-oil (Table II, ln_school_frac):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.784
Model:                            OLS   Adj. R-squared:                  0.779
Method:                 Least Squares   F-statistic:                     172.3
Date:                Tue, 23 Sep 2025   Prob (F-statistic):           2.47e-32
Time:                        18:52:48   Log-Likelihood:                -70.963
No. Observations:                  98   AIC:                             147.9
Df Residuals:                      95   BIC:                             155.7
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.8531      0.140     56.082      0.000       7.575       8.131
diff1          0.7383      0.124      5.972      0.000       0.493       0.984
diff2          0.6571      0.073      9.057      0.000       0.513       0.801
==============================================================================
Omnibus:                        2.571   Durbin-Watson:                   2.047
Prob(Omnibus):                  0.277   Jarque-Bera (JB):                2.582
Skew:                          -0.365   Prob(JB):                        0.275
Kurtosis:                       2.682   Cond. No.                         5.38
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

--- Intermediate Sample - Table II ---

Unrestricted OLS Summary for Intermediate (Table II, ln_school_frac):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.781
Model:                            OLS   Adj. R-squared:                  0.771
Method:                 Least Squares   F-statistic:                     84.25
Date:                Tue, 23 Sep 2025   Prob (F-statistic):           2.44e-23
Time:                        18:52:48   Log-Likelihood:                -45.257
No. Observations:                  75   AIC:                             98.51
Df Residuals:                      71   BIC:                             107.8
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              7.7913      1.192      6.534      0.000       5.414      10.169
ln_s               0.7004      0.151      4.651      0.000       0.400       1.001
ln_ngd            -1.4998      0.403     -3.720      0.000      -2.304      -0.696
ln_school_frac     0.7305      0.095      7.671      0.000       0.541       0.920
==============================================================================
Omnibus:                        2.500   Durbin-Watson:                   2.352
Prob(Omnibus):                  0.287   Jarque-Bera (JB):                1.944
Skew:                          -0.386   Prob(JB):                        0.378
Kurtosis:                       3.162   Cond. No.                         107.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Restricted OLS Summary for Intermediate (Table II, ln_school_frac):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.781
Model:                            OLS   Adj. R-squared:                  0.775
Method:                 Least Squares   F-statistic:                     128.1
Date:                Tue, 23 Sep 2025   Prob (F-statistic):           1.92e-24
Time:                        18:52:48   Log-Likelihood:                -45.268
No. Observations:                  75   AIC:                             96.54
Df Residuals:                      72   BIC:                             103.5
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.9662      0.154     51.582      0.000       7.658       8.274
diff1          0.7091      0.138      5.151      0.000       0.435       0.983
diff2          0.7330      0.093      7.874      0.000       0.547       0.919
==============================================================================
Omnibus:                        2.616   Durbin-Watson:                   2.336
Prob(Omnibus):                  0.270   Jarque-Bera (JB):                2.061
Skew:                          -0.398   Prob(JB):                        0.357
Kurtosis:                       3.156   Cond. No.                         5.82
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

--- OECD Sample - Table II ---

Unrestricted OLS Summary for OECD (Table II, ln_school_frac):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.352
Model:                            OLS   Adj. R-squared:                  0.244
Method:                 Least Squares   F-statistic:                     3.264
Date:                Tue, 23 Sep 2025   Prob (F-statistic):             0.0455
Time:                        18:52:48   Log-Likelihood:                -4.6190
No. Observations:                  22   AIC:                             17.24
Df Residuals:                      18   BIC:                             21.60
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              8.6369      2.214      3.901      0.001       3.985      13.289
ln_s               0.2761      0.389      0.710      0.487      -0.541       1.093
ln_ngd            -1.0755      0.756     -1.423      0.172      -2.664       0.513
ln_school_frac     0.7676      0.293      2.617      0.017       0.151       1.384
==============================================================================
Omnibus:                        0.378   Durbin-Watson:                   1.832
Prob(Omnibus):                  0.828   Jarque-Bera (JB):                0.167
Skew:                          -0.201   Prob(JB):                        0.920
Kurtosis:                       2.859   Cond. No.                         135.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Restricted OLS Summary for OECD (Table II, ln_school_frac):

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 ln_y85   R-squared:                       0.352
Model:                            OLS   Adj. R-squared:                  0.284
Method:                 Least Squares   F-statistic:                     5.167
Date:                Tue, 23 Sep 2025   Prob (F-statistic):             0.0161
Time:                        18:52:48   Log-Likelihood:                -4.6198
No. Observations:                  22   AIC:                             15.24
Df Residuals:                      19   BIC:                             18.51
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          8.7163      0.466     18.697      0.000       7.741       9.692
diff1          0.2829      0.334      0.847      0.407      -0.416       0.982
diff2          0.7686      0.284      2.704      0.014       0.174       1.364
==============================================================================
Omnibus:                        0.379   Durbin-Watson:                   1.838
Prob(Omnibus):                  0.827   Jarque-Bera (JB):                0.173
Skew:                          -0.204   Prob(JB):                        0.917
Kurtosis:                       2.853   Cond. No.                         15.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

 MRW Table I Replication:

                                                0             1         2
Table                                           I             I         I
Sample                                    Non-oil  Intermediate      OECD
Obs                                            98            75        22
CONSTANT (unres)                         5.429883      5.345865  8.020607
ln(I/GDP)                                1.424014      1.317553   0.49989
ln(n+g+δ)                               -1.989774     -2.017199 -0.741921
P-value (ln(I/GDP)) (unres)                   0.0           0.0  0.263572
P-value (ln(n+g+δ)) (unres)              0.000639      0.000322  0.394839
R2 (unres)                               0.592462      0.587767  0.011813
SEE (unres)                               0.68907      0.610641  0.377396
CONSTANT (res)                            6.87237      7.092921   8.62438
[ln(I/GDP) - ln(n+g+δ)]                  1.487994      1.430955  0.553845
P-value ([ln(I/GDP) - ln(n+g+δ)]) (res)       0.0           0.0  0.145129
R2 (res)                                 0.593166      0.586111  0.058241
SEE (res)                                0.688475      0.611866  0.368423

 MRW Table II Replication:

                                                 0             1         2
Table                                           II            II        II
Sample                                     Non-oil  Intermediate      OECD
Obs                                             98            75        22
CONSTANT (unres)                          6.844414      7.791314  8.636893
ln(I/GDP)                                 0.696709      0.700367  0.276134
ln(n+g+δ)                                -1.745247      -1.49978 -1.075506
ln(SCHOOL) (frac)                         0.654459      0.730549  0.767571
P-value (ln(I/GDP)) (unres)               0.000001      0.000015  0.486805
P-value (ln(n+g+δ)) (unres)               0.000062      0.000396  0.171947
P-value (ln(SCHOOL) (frac)) (unres)            0.0           0.0  0.017462
R2 (unres)                                0.778795      0.771425  0.244411
SEE (unres)                               0.507664      0.454704  0.330005
CONSTANT (res)                            7.853086      7.966237  8.716346
[ln(I/GDP) - ln(n+g+δ)]                   0.738285      0.709078   0.28287
[ln(SCHOOL) - ln(n+g+δ)]                  0.657079      0.733038  0.768571
P-value ([ln(I/GDP) - ln(n+g+δ)]) (res)        0.0      0.000002  0.407425
P-value ([ln(SCHOOL) - ln(n+g+δ)]) (res)       0.0           0.0  0.014072
R2 (res)                                   0.77939      0.774531  0.284125
SEE (res)                                 0.506981      0.451605  0.321215

Chosen SCHOOL scaling for Table II: fraction (0–1)

(  Table        Sample  Obs  CONSTANT (unres)  ln(I/GDP)  ln(n+g+δ)  \
 0     I       Non-oil   98          5.429883   1.424014  -1.989774
 1     I  Intermediate   75          5.345865   1.317553  -2.017199
 2     I          OECD   22          8.020607   0.499890  -0.741921

    P-value (ln(I/GDP)) (unres)  P-value (ln(n+g+δ)) (unres)  R2 (unres)  \
 0                 2.104645e-16                     0.000639    0.592462
 1                 5.383214e-11                     0.000322    0.587767
 2                 2.635722e-01                     0.394839    0.011813

    SEE (unres)  CONSTANT (res)  [ln(I/GDP) - ln(n+g+δ)]  \
 0     0.689070        6.872370                 1.487994
 1     0.610641        7.092921                 1.430955
 2     0.377396        8.624380                 0.553845

    P-value ([ln(I/GDP) - ln(n+g+δ)]) (res)  R2 (res)  SEE (res)
 0                             1.134081e-20  0.593166   0.688475
 1                             7.575889e-16  0.586111   0.611866
 2                             1.451291e-01  0.058241   0.368423  ,
   Table        Sample  Obs  CONSTANT (unres)  ln(I/GDP)  ln(n+g+δ)  \
 0    II       Non-oil   98          6.844414   0.696709  -1.745247
 1    II  Intermediate   75          7.791314   0.700367  -1.499780
 2    II          OECD   22          8.636893   0.276134  -1.075506

    ln(SCHOOL) (frac)  P-value (ln(I/GDP)) (unres)  \
 0           0.654459                 9.609054e-07
 1           0.730549                 1.487571e-05
 2           0.767571                 4.868051e-01

    P-value (ln(n+g+δ)) (unres)  P-value (ln(SCHOOL) (frac)) (unres)  \
 0                     0.000062                         2.442390e-14
 1                     0.000396                         6.792225e-11
 2                     0.171947                         1.746202e-02

    R2 (unres)  SEE (unres)  CONSTANT (res)  [ln(I/GDP) - ln(n+g+δ)]  \
 0    0.778795     0.507664        7.853086                 0.738285
 1    0.771425     0.454704        7.966237                 0.709078
 2    0.244411     0.330005        8.716346                 0.282870

    [ln(SCHOOL) - ln(n+g+δ)]  P-value ([ln(I/GDP) - ln(n+g+δ)]) (res)  \
 0                  0.657079                             4.039600e-08
 1                  0.733038                             2.171067e-06
 2                  0.768571                             4.074248e-01

    P-value ([ln(SCHOOL) - ln(n+g+δ)]) (res)  R2 (res)  SEE (res)
 0                              1.709027e-14  0.779390   0.506981
 1                              2.631555e-11  0.774531   0.451605
 2                              1.407250e-02  0.284125   0.321215  )